project:
  type: website
  output-dir: docs

website:
  title: "Kevin Lingfeng Li"
  navbar:
      title: "Kevin Lingfeng Li"
      search: true
      pinned: true
      left:
        - text: "Projects"
          href: projects.qmd
        - text: "Music"
          href: music.qmd
        - text: "Education"
          href: education.qmd
        - text: "DiD Resources"
          href: https://kevinli03.github.io/did/
        - text: "Causal Inference"
          href: https://kevinli03.github.io/causal/

format:
  html:
    theme: default
    css: styles.css
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 700px
      margin-width: 200px
      gutter-width: 2em
    fontsize: 11pt
    toc: false
    toc-title: "On This Page"
    html-math-method: mathjax
    include-in-header:
      text: |
        <script src="mathjax-config.js"></script>
editor: visual

