---
title: "Kevin Lingfeng Li"
subtitle: "MSc Student, London School of Economics"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float:
      collapsed: false
    toc_depth: 4
    theme: lumen
---

```{=html}
<style>
  body .main-container {
    max-width: 1100px;
    font-size: 15px;
  }
</style>
```
<br />

# **Hello!**

### About me

I am a student at the London School of Economics, studying for a MSc in Political Science & Political Economy. My interests relate to the use of statistics and formal mathematical modelling to study political science and political economy.

Prior to my MSc, I completed a BSc (Hons) in Politics from King's College London, receiving First Class Honours (US Equivalent: Summa Cum Laude). During my undergraduate degree, I also took summer courses in Data Science and Machine Learning at the London School of Economics.

<br />

My work experience includes two internships with the United Nations Development Programme. My first internship was with the Foresight Team within the Regional Bureau of Asia and the Pacific. There, I contributed to a publication on the potential effects of climate migration on Pakistan and Vietnam, and helped draft potential policy solutions. I, along with my colleagues, organised an online consultation with local stakeholders in Pakistan and Vietnam to facilitate inclusive policy-making.

My second internship was with the inclusive growth team of the Bureau for Programme and Policy Support. There, I contributed to a publication on UNDP's effectiveness in promoting the Samoa Plan of Action for Small Islands and Developing States (SIDS). I also worked on a database of "best practices" regarding UNDP social protection programmes.

<br />

Also, fun fact (also a little bit of a brag), but I was offered a place on the MPhil Politics and International Studies programme at the University of Cambridge. I ended up choosing the London School of Economics over Cambridge, mainly because my interests lie in Political Economy and economic methods in studying politics.

<br />

This is my personal website. I don't really have a purpose for this site, besides using it to post some of my accomplishments or what I find interesting!

<br />

### Contact

LinkedIn: <https://www.linkedin.com/in/kevinlingfengli/>

Email: k.l.li1\@lse.ac.uk

<br />

------------------------------------------------------------------------

# **Publications**

### Co-Authored

Rubian, Renata, Dajna Sorenson, Rishi Chakraborty, Kevin Li, and Jade Cooper. “SIDS: Looking Back and Forward – Accelerating Action in the Next 10 Years.” *United Nations Development Programme*, (May 2024). <https://www.undp.org/publications/sids-looking-back-and-forward>

Internal Site Link: <https://kevinli03.github.io/publications/undp-sids.pdf>

<br />

### Contributed/Acknowledged

Krishnan, Aarathi, Beth Allen, Sophia Robele, Aaron Martin, Wajiha Khan. "Anticipating the Impacts of Climate Change Related Human Mobility in Pakistan and Viet Nam: Insights from a Participatory Foresign Process", *United Nations Development Programme*, (Sep 2024).

<https://www.undp.org/asia-pacific/publications/anticipating-impacts-of-climate-change-related-human-mobility-pakistan-and-viet-nam>

Internal Site Link: <https://kevinli03.github.io/publications/undp-climatemigration.pdf>

<br />

------------------------------------------------------------------------

# **Projects/Cool Stuff**

### Political Science Handbook

-   <http://politicalscience.github.io>

-   This is a handbook of all the methods I have learned throughout my years studying political science, all in one place that I and others can reference.

<br />

### VOC and Tax Dataset

-   <https://github.com/kevinli03/VocTaxDataset>

-   This is a dataset that I created on the Varieties of Capitalism Framework (Political Economy) for an undergraduate paper. It includes OECD countries, their respective Variety of Capitalism as defined by the Varieties of Capitalism Framework, and relevant tax levels and economic data on the countries.

<br />

### 2024-2025 Notes

To see my notes for the 2024-2025 school year, see the link below.

-   Note: these notes are not meant to be "publishable", they may contain mistakes, and may not be organised perfectly. They were taken during lectures/videos/readings that I have done.

[kevinli03.github.io/notes](https://kevinli03.github.io/notes/)

<br />

------------------------------------------------------------------------

# **Full Academic History**

### London School of Economics (MSc)

[**Programme Details**]{.underline}:

Programme: **MSc Political Science and Political Economy (Specialisation in Applied Statistics/Econometrics)**

Institution: **London School of Economics and Political Science (LSE)**

-   Dates: September 2024 - September 2025

-   Final Classification: N/A (no predicted grades yet)

-   Dissertation Topic:

-   Dissertation Supervisor:

-   Academic Mentor: Professor Torun Dewan

<br />

[**Courses:**]{.underline}

Registered Modules:

-   MY452 Applied Regression Analysis (Prof. Jouni Kuha)

-   MY455 Multivariate Analysis (Prof. Jouni Kuha)

-   MY457 Causal Inference for Observational and Experimental Studies (Dr. Daniel de Kadt)

-   GV481 Quantitative Analysis for Political Science (Dr. Aliz Tóth, Dr. Felipe Torres-Raposo)

-   GV4C8 Game Theory for Political Science (Prof. Rafael Hortala-Vallve, Dr. Kun Byeonggeun Heo)

-   GV482 Current Issues in Political Economy (Prof. Stephane Wolton)

-   GV499 Dissertation

<br />

Audited Modules

-   MY470 Computer Programming (Dr. Milena Tsvetkova)

-   ST304 Time Series and Forecasting

<br />

Pre-Sessional Courses:

-   GV4L8 Introductory Mathematics for Political Science (Dr. Marta Antonetti)

-   GV4L9 Introductory R for Political Science (Dr. Marta Antonetti)

-   EU409 Basic Economic Concepts

<br />

### LSE Summer School

[**Programme Details**]{.underline}:

Programme: **LSE Summer School - Data Science and Accounting**

Institution: **London School of Economics and Political Science (LSE)**

-   Dates: July 2024 - August 2024

-   Final Classification: A+ (First Class)

<br />

[**Courses:**]{.underline}

-   ME314 Introduction to Data Science & Machine Learning (Dr. Kenneth Benoit, Dr. Jack Blumenau)

-   AC110 Principles of Accounting (Dr. Jeroen Koenraadt, Dr. Gulnaz Khamidullina)

<br />

### King's College London (BSc)

[**Programme Details**]{.underline}:

Programme: **BSc (Honours) in Politics**

Institution: **King's College London**

-   Dates: September 2021 - July 2024

-   Final Classification: First Class Honours

-   Academic Mentor: Dr. James Scott, Dr. Teresa Esteban-Casanelles

<br />

[**Courses:**]{.underline}

3rd Year Courses:

-   6SSPP330 Economic Policy-Making (Dr. Julian Limberg)

-   6SSPP403 Advanced Game Theory (Dr. Mehmet Ismaili)

-   6SSPP364 Key Issues in Policy Making (Prof. Kristel Koop)

-   6SSPP388 Environmental Governance (Dr. Francesca Pia Vantaggiato)

-   6SSPP American Foreign Policy (Dr. Keith Smith)

-   6SSPP341 Global Power Europe (Dr. Thomas Maltby)

-   6SSPP356 Authoritarianism (Prof. Sarah Birch)

-   6SSPP360 Elections and Voting Behaviour (Dr. Krzysztof Krakowski)

<br />

2nd Year Courses:

-   5SSPP241 Statistics for Political Science II (Dr. Damien Bol)

-   5SSPP227 Game Theory and Strategic Decision Making (Prof. Paul Lewis, Dr. Mehmet Ismail)

-   5SSPP206 Research Methods for Politics (Dr. Hanna Kleider)

-   5SSPP231 Policy Analysis: Decision, Implementation, and Evaluation (Dr. John Meadowcroft)

-   5SSPP223 Issues in International Politics (Dr. Keith Smith)

-   5SSPP240 American Political Development (Dr. Samuel DeCanio)

-   5SSPP205 Political Change in Europe (Dr. Teresa Esteban-Casanelles)

-   5SSPP242 British Politics (Prof. Peter John)

<br />

1st Year Courses:

-   4SSPP111 Statistics for Political Science (Dr. Adam Chalmers)

-   4SSPP101 Fundamentals of Politics Research (Prof. Adrian Blau)

-   4SSPP102 World Politics Since 1945 (Dr. Keith Smith, Dr. Jonathan Leader Manyard)

-   4SSPP103 Comparing Political Systems (Dr. Damien Bol, Dr. Julian Limberg)

-   4SSPP104 Introduction to Political Theory (Dr. Steven Klein, Dr. Billy Christmas)

<br />

### Canyon Crest Academy (ACT, AP)

[**Programme Details**]{.underline}:

Programme: **High School Diploma, Advanced Placement (AP), ACT**

Institution: **King's College London**

-   Dates: September 2017 - June 2021

-   Awards: National AP Scholar, AP Scholar with Distinction (3x), President's Volunteer Service Award (2x)

<br />

**ACT Standardised Test**:

Overall score: 35/36

-   Reading: 35/36

-   English: 35/36

-   Math: 35/36

-   Science: 36/36

<br />

**AP Tests and Courses:**

-   AP Calculus BC

-   AP Statistics

-   AP Physics 1

-   AP Physics 2

-   AP Chemistry

-   AP Computer Science Principles

-   AP Macroeconomics

-   AP English Language and Composition

-   AP English Literature and Compoisition

-   AP United States Government and Politics

-   AP World History: Modern

-   AP United States History

-   AP European History

-   AP Psychology

-   AP Chinese Language and Culture

-   AP Music Theory
