---
title: "Quantitative Methods"
subtitle: "Companian to the series: Introduction to Political Economics"
author: "Kevin Lingfeng Li"
format:
    pdf:
        toc: true
        toc-depth: 2
        documentclass: report
        papersize: A4
        geometry:
            - width=150mm
            - height=238mm
            - top=27mm
        number-sections: true
        number-depth: 3
        top-level-division: part
        linestretch: 1.25
---

## Preface {.unnumbered}

This book is one of the 3 **mathematical-companian-guides** of the part of a series: **Introduction to Political Economics**. These companian guides are meant to ensure that one has the proper mathematical training prior to studying Political Economics:

1.  **Quantitative Methods** (This Book) introduces the essential mathematical concepts that are essential for studying Political Economics. Topics include single variable calculus, introductory linear algebra, and introductory probability and statistical theory.
2.  **Further Quantitative Methods** expands on the topics taught in the previous book. While these topics are not absolutely essential for Political Economics, they can be highly useful for a deeper understanding of Political Economics. Topics include advanced linear algebra and multivariate calculus.
3.  **Introductory Proofs and Analysis** is a high-level introduction to proofs in mathematics. This is not essential for studying Political Economics, but having a strong idea behind proofs is quite useful for more advanced Microeconomic Models that are used in the study of Political Economics.

This book, Quantitative Methods, is a collection of mathematical and statistical topics that I consider to be essential to understand prior to starting any serious instruction in Political Economics. The book assumes a solid understanding of high-school level algebra, and discusses topics in single variable calculus, introductory linear algebra, and probability and statistical theory. Note that this book is not a full mathematics course of those topics - topics have been selected based on what is commonly used in Political Economics and other social sciences.

# Single Variable Calculus

## Pre-Calculus

### Set Theory

A **set** is a collection of objects. The objects within a set are the **elements** of that set.

We can define a set by either listing every element out, or through describing the properties of the elements of the set.

-   For example, $A = \{1,2,3,4,5\}$

-   Or, $A=\{n|n \in \mathbb{Z}; 1 ≤ n ≤ 5\}$ - or in other words, $A$ is the set of values $n$, *such that* $n$ is in the set of all *integers* $Z$, and $n$ is between 1 and 5 inclusive.

Here are some common notation for sets:

-   If two sets $A$ and $B$ have the same elements, they are equal: $A = B$.

-   If $a$ is an element of set $A$, we use the notation: $a \in A$.

-   If $a$ is not an element of set $A$, we use the notation: $a \notin A$.

-   If all elements of set $A$ are also within set $B$, then it is considered a **subset**, and notated $A \subseteq B$.

-   If $A \subseteq B$, but $A ≠ B$, then $A$ is a **proper subset** of $B$, notated: $A \subset B$.

There are a few common **operations** of sets:

-   The **union** of sets $A$ and $B$, notated $A \cup B$, is the set of elements that belong to either $A$ [or]{.underline} $B$. For example, if $A = \{1,2,3\}, B = \{3,4,5\}$, then $A \cup B = \{1,2,3,4,5\}$.

-   The **intersection** of sets, notated $A \cap B$, is the set of elements that belong to $A$ [and]{.underline} $B$. For example, if $A = \{1,2,3\}, B = \{3,4,5\}$, then $A \cap B = \{3\}$.

The **cardinality** of a set $A$ is the number of elements within set $A$, and is notated $|A|$. For example, if $A = \{1,2,3\}$, then $|A| = 3$. An **empty set** is a set with a cardinality of 0, or in other words, with no elements. It is notated with $\varnothing$

A **infinite set** is one with infinitely many elements. Common examples of infinite sets include:

-   Set of all natural numbers $\mathbb{N} = \{1,2,3,...\}$.

-   Set of all integers $\mathbb{Z} = \{..., -2, -1, 0, 1, 2, ... \}$.

-   Set of all rational numbers $\mathbb{Q}$, which are all numbers that can be written in a fraction (so excluding numbers like $\pi$).

-   Set of all real numbers $\mathbb{R}$, which is any number on the real number line.

The set of all real numbers $\mathbb{R}$ is the most common used set. A subset of $\mathbb{R}$ is called an **interval**, and can be notated with either brackets or parentheses as follows:

-   Closed interval: $[a,b] = \{  x \in \mathbb{R} | a ≤ x ≤ b \}$

-   Open interval: $(a, b) = \{ x \in \mathbb{R}|a < x < b \}$

-   We can also mix closed and open intervals: $[a, b) = \{ x \in \mathbb{R}|a≤x<b\}$

In all these intervals, $a$ and $b$ are called **endpoints** of the interval. Any point inside of an interval that is not an endpoint is an **interior point**.

### Exponents, Logarithms, Sum and Product Notation

### Functions and the Cartesian Plane

### Special Types of Functions

### Limits and Continuity


## Derivatives

### Definition of a Derivative

### Rules of Differentiation

### Derivative of an Inverse Function

### Partial Derivatives

### Application: Linear Regression


## Optimisation

### Local Extrema and Stationary Points

### Concavity and Inflextion Points

### Global Extrema

### Optimisation Without Constraints

### Application: Linear Regression Estimation

### Simple Optimisation With Constraints



## Integrals

### Indefinite Integrals

section 9.1 and 9.3

### Definite Integrals and Riemann Sums

### Fundamental Theorem of Calculus

### Integration by Recognition

### Integration by Substitution

### Integration by Parts

### Integration by Partial Fractions

### Application: Consumer and Producer Surplus



# Introductory Linear Algebra

## Matrices


### Matrix Operations

topics 3.2-3.3

### Inverse Matrix

### Simple Linear Systems of Square Matrix

### Elementary Row Operations and Reduced Row Echelon Form

### Theorems on Matrix Invertibility

### Determinant of a Matrix

### Linear Systems of Invertible Square Matrix


## General Linear Systems

### Geometric Insight of a 2-Dimensional Plane

### K-dimensional Flats

### Solving Lienar Systems of Equations

### Solution Sets and Linearity

### Analysing Solution Sets with the Rank

# Probability and Statistical Theory

## Probability Theory
### Rules of Probability

### Counting

### Independence and Conditional Probability

### Law of Total Probability

### Bayes' Theorem



## Random Variables

### Discrete Random Variables

### Continuous Random Variables

### Expectations

### Moments



## Distributions

### Discrete Uniform and Bernoulli Distribution

### Binomial and Poisson Distribution

### Continous Uniform and Exponential Distribution

### Normal (Gaussian) Distribution

### Normal Approximation of the Binomial Distribution


## Multivariate Random Variables

### Joint Probability Functions

### Marginal Distributions

### Continuous Multivaraite Distributions

### Conditional Distributions

### Covariance and Correlation

### Independent Random Variables

### Sums and Products of Random Variables