---
title: "Mathematical Methods for Political Science"
subtitle: "Kevins' Guide to Political Science and Political Economy"
author: "Kevin Lingfeng Li"
format:
    pdf:
        toc: true
        toc-depth: 2
        documentclass: report
        papersize: A4
        geometry:
            - width=150mm
            - height=238mm
            - top=27mm
        number-sections: true
        number-depth: 3
        top-level-division: part
        linestretch: 1.25
---

## Preface {.unnumbered}

This book is part of a 5-part series: **Kevin's Guide to Political Science and Political Economy**:

1.  **Quantitative Methods and Analysis** introduces many of the core statistical concepts and methods used in Political Science and Social Science research. This book mainly covers Linear Regression models and techniques of Causal Inference.
2.  **Game Theory and Formal Models** introduces key concepts in the field of Game Theory, which has become a very popular tool to model and study political situations. This book starts off with Static Games, before moving to Dynamic Games and Bayesian Games.
3.  **Topics in Quantitative Political Research** applies the econometric and game theory techniques in the previous two books to the study of current issues in Political Science and Political Economy.
4.  **Advanced Quantitative Methods** provides higher-level statistical techniques for Political Science and Political Economy, building on the first book. This book mainly covers logit and count regression models, time series models, and latent variable models.
5.  **Data Science and Political Analysis** introduces modern statistical learning techniques that have improved prediction accuracy. The book starts off with prediction and classification methods, then covers model validation, before ending on text mining and quantitative text analysis.

This book on Mathematical Methods is designed to give the mathematical background neccesary for a rigorous understanding of methods and techniques in Political Science and Political Economy. Not all topics in this book are essential - you can likely get by with only the first few chapters - however, having a strong understanding of mathematics is critical to obtaining a strong understanding of methods, which is an important part of becoming a strong researcher. This book assumes prior knowledge up to High School Algebra.

# Single Variable Calculus

## Pre-Calculus Topics

### Set Theory

A **set** is a collection of objects. The objects within a set are the **elements** of that set.

We can define a set by either listing every element out, or through describing the properties of the elements of the set.

-   For example, $A = \{1,2,3,4,5\}$

-   Or, $A=\{n|n \in \mathbb{Z}; 1 ≤ n ≤ 5\}$ - or in other words, $A$ is the set of values $n$, *such that* $n$ is in the set of all *integers* $Z$, and $n$ is between 1 and 5 inclusive.

Here are some common notation for sets:

-   If two sets $A$ and $B$ have the same elements, they are equal: $A = B$.

-   If $a$ is an element of set $A$, we use the notation: $a \in A$.

-   If $a$ is not an element of set $A$, we use the notation: $a \notin A$.

-   If all elements of set $A$ are also within set $B$, then it is considered a **subset**, and notated $A \subseteq B$.

-   If $A \subseteq B$, but $A ≠ B$, then $A$ is a **proper subset** of $B$, notated: $A \subset B$.

There are a few common **operations** of sets:

-   The **union** of sets $A$ and $B$, notated $A \cup B$, is the set of elements that belong to either $A$ [or]{.underline} $B$. For example, if $A = \{1,2,3\}, B = \{3,4,5\}$, then $A \cup B = \{1,2,3,4,5\}$.

-   The **intersection** of sets, notated $A \cap B$, is the set of elements that belong to $A$ [and]{.underline} $B$. For example, if $A = \{1,2,3\}, B = \{3,4,5\}$, then $A \cap B = \{3\}$.

The **cardinality** of a set $A$ is the number of elements within set $A$, and is notated $|A|$. For example, if $A = \{1,2,3\}$, then $|A| = 3$. An **empty set** is a set with a cardinality of 0, or in other words, with no elements. It is notated with $\varnothing$

A **infinite set** is one with infinitely many elements. Common examples of infinite sets include:

-   Set of all natural numbers $\mathbb{N} = \{1,2,3,...\}$.

-   Set of all integers $\mathbb{Z} = \{..., -2, -1, 0, 1, 2, ... \}$.

-   Set of all rational numbers $\mathbb{Q}$, which are all numbers that can be written in a fraction (so excluding numbers like $\pi$).

-   Set of all real numbers $\mathbb{R}$, which is any number on the real number line.

The set of all real numbers $\mathbb{R}$ is the most common used set. A subset of $\mathbb{R}$ is called an **interval**, and can be notated with either brackets or parentheses as follows:

-   Closed interval: $[a,b] = \{  x \in \mathbb{R} | a ≤ x ≤ b \}$

-   Open interval: $(a, b) = \{ x \in \mathbb{R}|a < x < b \}$

-   We can also mix closed and open intervals: $[a, b) = \{ x \in \mathbb{R}|a≤x<b\}$

In all these intervals, $a$ and $b$ are called **endpoints** of the interval. Any point inside of an interval that is not an endpoint is an **interior point**.

### Functions

### Catesian Equations and Graphs

### Surjective, Injective, and Bijective Functions

A

## Derivatives

topics 1.6-1.9

## Optimisation

topics 2.2-2.9

## Integrals

topics 9.1 - 9.3

## Advanced Integration

topics 9.4-9.7

# Linear Algebra

## Introduction to Matrices

topics 3.1

## Matrix Operations

topics 3.2-3.3

## Simple Linear Systems

## General Linear Systems

## Vector Spaces

## Linear Operators and Diagonalisation

# Multivariate Calculus